### ISSUE TITLE
http header 디버깅: echoserver

### ISSUE THREAD

**Issue by hakchangs** [hakchangs/k8s-study#16]
**echoserver** 이미지로 http header 추적이 가능하다.

### debug 상황
- Reverse Proxy 를 사용할때 `Forwarded` , `X-Forwarded-*` 헤더가 생성되 전달되었는지 확인

#### 1. kubectl 반영
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoheaders
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoheaders
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoheaders
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: echoheaders
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoheaders
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: echo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoheaders
            port:
              number: 80
```

#### 2. 테스트 및 헤더확인
```shell
curl https://echo.local -vk
```
```

Hostname: echoheaders-5946468fd9-gcsgh

Pod Information:
	-no pod information available-

Server values:
	server_version=nginx: 1.13.3 - lua: 10008

Request Information:
	client_address=10.42.0.67
	method=GET
	real path=/
	query=
	request_version=1.1
	request_scheme=http
	request_uri=http://echo.local:8080/

Request Headers:
	accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
	accept-encoding=gzip, deflate, br, zstd
	accept-language=en-US,en;q=0.5
	cache-control=no-cache
	host=echo.local
	pragma=no-cache
	priority=u=0, i
	sec-fetch-dest=document
	sec-fetch-mode=navigate
	sec-fetch-site=none
	sec-fetch-user=?1
	upgrade-insecure-requests=1
	user-agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0
	x-forwarded-for=192.168.122.1
	x-forwarded-host=echo.local
	x-forwarded-port=443
	x-forwarded-proto=https
	x-forwarded-scheme=https
	x-real-ip=192.168.122.1
	x-request-id=4b3aec37ebf3758d72b529784a6c8ade
	x-scheme=https

Request Body:
	-no body in request-

```
