### ISSUE TITLE
Cilium: Hubble 설치하고 모니터링하기

### ISSUE THREAD

**Issue by hakchangs** [hakchangs/k8s-study#26]
> https://docs.cilium.io/en/stable/observability/hubble/setup/

hubble 설치하면 네트워크 트래픽 모니터링이 가능하다.
hubble client 까지 설치하여 4245 포트로 로그를 관찰할 수 있다.

### helm 설정
```yaml
kubeProxyReplacement: "true"
k8sServiceHost: "192.168.122.30"
k8sServicePort: "6443"
hubble:
  ui:
    enabled: true
  relay:
    enabled: true
```
