### ISSUE TITLE
APISIX: kube-api 라우팅

### ISSUE THREAD

**Issue by hakchangs** [hakchangs/k8s-study#45]
## kube-api 라우팅하기

```yaml
{
  "uri": "/*",
  "name": "kube-api",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "k8s.local",
  "plugins": {
    "cors": {
      "_meta": {
        "disable": false
      },
      "allow_credential": false,
      "allow_headers": "*",
      "allow_methods": "*",
      "allow_origins": "*",
      "expose_headers": "*",
      "max_age": 5
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "kubernetes.default.svc",
        "port": 443,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "https",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```

### 주요옵션
- `upstream.nodes[].host`
kubernetes.default.svc 로 라우팅 서비스를 지정한다.
- `plugins.cors`
swagger-ui 에 openapi 규격을 노출하고 싶다면, `Access-Control-Allow-Origin: *` 설정을 해준다.
설정이 없다면 브라우저에서 cors 오류를 발생시킨다.

### kube-apiserver api 규격 노출
`/openapi/v2` 로 규격만 받아오려고 해도 인증을 요청하며 401 오류를 발생시킨다.

kube-apiserver 설정을 통해 모두 접근하도록 할 수 있다.
시스템 익명 사용자가 접근하도록 kube-apiserver 옵션, ClusterRoleBinding 을 설정해준다.

#### 1. kube-apiserver 옵션변경
```yaml
spec:
  containers:
  - name: kube-apiserver
    command:
    - kube-apiserver
    - --anonymous-auth=true
    - --authorization-mode=RBAC
```

#### 2. 익명사용자를 위한 ClusterRole, ClusterRoleBinding 추가
```yaml
# /openapi/v2 만 허용
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openapi-viewer
rules:
- nonResourceURLs: ["/openapi/v2"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openapi-anonymous
subjects:
- kind: User
  name: system:anonymous
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: openapi-viewer
  apiGroup: rbac.authorization.k8s.io
```

### kube-apiserver 인증처리
kube-api openapi 규격은 Authorization 헤더 + bearer 인증을 요청한다.
토큰을 획득하여 설정후 요청하면 된다.
