### ISSUE TITLE
APISIX: 서브 도메인 기반 라우팅

### ISSUE THREAD

**Issue by hakchangs** [hakchangs/k8s-study#47]
NodePort 로 기본설치되는데 포트명시 없이 접속될까?

### 서브도메인 기반 라우팅

apisix = apisix.local
swagger = **swagger**.apisix.local
keycloak = **keycloak**.apisix.local

helm 설정
```yaml
#values.yaml
ingress:
  enabled: true
  hosts:
    - host: "*.apisix.local"
      paths:
      - "/"
```
